apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "monadium-deployment"
  namespace: "default"
  labels:
    app: "monadium"
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: "monadium"
  template:
    metadata:
      labels:
        app: "monadium"
    spec:
      containers:
        - image: var-monadium
          name: monadium
