name: CD

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1
        id: cache

      - name: Echo Cache Hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo Cache-hit

      - name: Echo Cache Miss
        if: steps.cache.outputs.cache-hit == 'false'
        run: echo Cache-miss

      - name: Cargo Build
        run: |
          cargo build --release
          cargo test --release

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: GCloud Auth Docker
      - run: |
          gcloud auth configure-docker -q

      - name: Docker Build
        run: |
          docker build -t eu.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} .

      # Push image to Google Container Registry
      - name: Docker Push
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Cloud Run Deploy
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
          --image eu.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region europe-north1 \
          --allow-unauthenticated \
          --memory 256M \
          --max-instances 1 \
          --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
          --set-env-vars "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
          --set-env-vars "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" \
          --set-env-vars "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}"
