name: CD

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Setup GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          export_default_credentials: true

      - name: Setup Docker For GCP
        run: |
          gcloud auth configure-docker -q

      - name: Cargo Build
        run: cargo build --release

      - name: Cargo Test
        run: cargo test --release

      - name: Docker Build
        run: |
          docker build -t eu.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} .

      - name: Docker Push
        run: |-
          docker push eu.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

      - name: Cloud Run Deploy
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
          --image eu.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region europe-north1 \
          --allow-unauthenticated \
          --memory 256M \
          --max-instances 1 \
          --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
          --set-env-vars "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
          --set-env-vars "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" \
          --set-env-vars "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}"
