name: CI

on:
  push:
    branches:
      - "main"

env:
  DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
  GIT_EMAIL: marcus+monadium-ci@radell.net

  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  INFRA_REPO_TOKEN: ${{ secrets.INFRA_REPO_TOKEN }}
  IMAGE_URL: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/monadium:${{ github.sha }}

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: debug cache key
        run: echo ${{ runner.os }}-sqlx-${{ hashFiles('scripts/install-sqlx.sh')}}

      - name: debug cache hit
        run: echo steps.cache-sqlx.outputs.cache-hit

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Cache Sqlx
        id: cache-sqlx
        uses: actions/cache@v2
        with:
          path: /usr/local/cargo
          key: ${{ runner.os }}-sqlx-${{ hashFiles('scripts/install-sqlx.sh')}}

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Docker For GCP
        run: |
          gcloud auth configure-docker -q

      - name: Install sqlx cli
        if: steps.cache-sqlx.outputs.cache-hit != 'true'
        run: ./scripts/install-sqlx.sh

      - name: Init DB
        run: ./scripts/init-db.sh

      - name: Cargo Build
        run: cargo build --release

      - name: Cargo Test
        run: cargo test --release

      - name: Docker Build
        run: docker build -t $IMAGE_URL .

      - name: Docker Push
        run: docker push $IMAGE_URL

      - name: Checkout infra repository
        uses: actions/checkout@v2
        with:
          repository: marcusradell/monadium-infra
          token: ${{ env.INFRA_REPO_TOKEN }}
          path: infra

      - name: Push to infra
        run: |
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GITHUB_ACTOR"
          cd infra/k8s/base/monadium
          kustomize edit set image var-image=$IMAGE_URL
          git commit -am "Deploy new image $IMAGE_URL"
          git push
