name: Docker Copy Only No Cache

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          cargo build --release
          cargo test --release

      - name: Build image
        run: |
          docker build -t eu.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{github.sha}} -f Dockerfile.copy_only .
